import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import Header from "@/components/Header/Header"
import {
    hasLocale,
    NextIntlClientProvider,
} from "next-intl"
import { routing } from "@/i18n/routing"
import { notFound } from "next/navigation"
import { setRequestLocale } from "next-intl/server"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode
    params: Promise<Record<string, unknown>>
}>) {
    const { locale } = await params
    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }
    setRequestLocale(locale)
    return (
        <html lang={locale}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <AntdRegistry>
                    <Header />
                    <NextIntlClientProvider>
                        {children}
                    </NextIntlClientProvider>
                </AntdRegistry>
            </body>
        </html>
    )
}
